# Generated by Django 4.2 on 2024-03-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tur',
            field=models.CharField(choices=[('ENG', 'Engyaxshi Chegirmalar'), ('YNM', 'Sara Tavarlar'), ('KUN', "So'ngi va o'rtacha maxsulotlar")], default='ENG', max_length=50),
        ),
    ]
