# Generated by Django 4.2 on 2024-03-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('image', models.ImageField(upload_to='category/')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-name'], name='category_ca_name_68669f_idx'),
        ),
    ]
